FROM python:3.12-slim

WORKDIR /app
ENV PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1

COPY requirements-astroos.txt ./
RUN pip install --no-cache-dir -r requirements-astroos.txt
COPY astroos ./astroos
COPY schemas ./schemas

CMD ["python", "-m", "astroos"]
